// Exact legacy role filenames only. New CMS uploads remain authoritative.
// Assets are checked for transparency by the storefront regression audit.
export const approvedProductCutouts: Record<string, string> = {
  "masport-500": "/images/products/cutouts/masport-500.webp",
  "jalupro-hmw": "/images/products/cutouts/jalupro-hmw.webp",
  "inovosense-style": "/images/products/cutouts/inovosense-style.webp",
  "inovosense-shape": "/images/products/cutouts/inovosense-shape.webp",
  "hyalase-1500": "/images/products/cutouts/hyalase-1500.webp",
  "perleux": "/images/products/cutouts/perleux.webp",
  "jalupro-super-hydro": "/images/products/cutouts/jalupro-super-hydro.webp",
  "neuramis-volume-1ml": "/images/products/cutouts/neuramis-volume-1ml.webp",
  "alcarisa-20": "/images/products/cutouts/alcarisa-20.webp",
  "hyaron": "/images/products/cutouts/hyaron.webp",
  "revofil-1ml": "/images/products/cutouts/revofil-1ml.webp",
  "dyston-500": "/images/products/cutouts/dyston-500.webp",
  "ejal-40": "/images/products/cutouts/ejal-40.webp",
  "kiara-reju": "/images/products/cutouts/kiara-reju.webp",
  "eptq-1ml": "/images/products/cutouts/eptq-1ml.webp",
  "neuramis-deep-1ml": "/images/products/cutouts/neuramis-deep-1ml.webp",
  "jalupro-classic": "/images/products/cutouts/jalupro-classic.webp",
  "cg-dimono-ptx": "/images/products/cutouts/cg-dimono-ptx.webp",
  "alcarisa-24": "/images/products/cutouts/alcarisa-24.webp",
  "luxiva": "/images/products/cutouts/luxiva.webp",
  "inovosense-smile": "/images/products/cutouts/inovosense-smile.webp",
  "audrey-m": "/images/products/cutouts/audrey-m.webp",
  "hyamax-contour": "/images/products/cutouts/hyamax-contour.webp",
  "audrey-h": "/images/products/cutouts/audrey-h.webp",
  "alcarisa-16": "/images/products/cutouts/alcarisa-16.webp",
  "neuramis-lido-1ml": "/images/products/cutouts/neuramis-lido-1ml.webp",
  "dr-cyj-hair-filler": "/images/products/cutouts/dr-cyj-hair-filler.webp",
  "rabianca-70ml": "/images/products/cutouts/rabianca-70ml.webp",
  "liporase-1500": "/images/products/cutouts/liporase-1500.webp",
  "alcarisa-28": "/images/products/cutouts/alcarisa-28.webp",
  "neuramis-lido-10-pack": "/images/products/cutouts/neuramis-lido-10-pack.webp",
  "neuramis-deep-10-pack": "/images/products/cutouts/neuramis-deep-10-pack.webp",
  "eptq-s100": "/images/products/cutouts/eptq/eptq-s100.webp",
  "eptq-s300": "/images/products/cutouts/eptq/eptq-s300.webp",
  "eptq-s500": "/images/products/cutouts/eptq/eptq-s500.webp",
  "product-fusion": "/images/products/cutouts/drive/product-fusion.webp",
  "product-jalupro": "/images/products/cutouts/drive/product-jalupro.webp",
  "product-revofil": "/images/products/cutouts/drive/product-revofil.webp",
  "siax-200": "/images/products/cutouts/sourced/siax-200.webp",
  "rabianca": "/images/products/cutouts/sourced/rabianca.webp",
  "f-eye-contour": "/images/products/cutouts/sourced/f-eye-contour.webp",
  "siax-100": "/images/products/cutouts/sourced/siax-100.webp",
  "f-vitamin-c": "/images/products/cutouts/sourced/f-vitamin-c.webp",
  "fusion-f-radiance": "/images/products/cutouts/sourced/fusion-f-radiance.webp",
  "mesolike-top-age-pro": "/images/products/cutouts/sourced/mesolike-top-age-pro.webp",
  "f-mesomatrix": "/images/products/cutouts/sourced/f-mesomatrix.webp",
  "sofiderm-derm-plus": "/images/products/cutouts/sourced/sofiderm-derm-plus.webp",
  "myobloc": "/images/products/cutouts/sourced/myobloc.webp",
  "fusion-hair-men": "/images/products/cutouts/sourced/fusion-hair-men.webp",
  "regenfill-lido": "/images/products/cutouts/sourced/regenfill-lido.webp",
  "regenfill-deep": "/images/products/cutouts/sourced/regenfill-deep.webp",
  "zishel-rose-glam": "/images/products/cutouts/sourced/zishel-rose-glam.webp",
  "f-melirutin": "/images/products/cutouts/sourced/f-melirutin.webp",
  "dysport-500": "/images/products/cutouts/sourced/dysport-500.webp",
  "neuramis-volume-lidocaine": "/images/products/cutouts/sourced/neuramis-volume-lidocaine.webp",
  "f-hair": "/images/products/cutouts/sourced/f-hair.webp",
  "mesolike-lift": "/images/products/cutouts/sourced/mesolike-lift.webp",
  "fusion-lift-face": "/images/products/cutouts/sourced/fusion-lift-face.webp",
  "dermaheal-hsr": "/images/products/cutouts/sourced/dermaheal-hsr.webp",
  "regenfill-volume": "/images/products/cutouts/sourced/regenfill-volume.webp",
  "neuramis-lidocaine": "/images/products/cutouts/sourced/neuramis-lidocaine.webp",
  "norafill-deep": "/images/products/cutouts/sourced/norafill-deep.webp",
  "nabota-150": "/images/products/cutouts/sourced/nabota-150.webp",
  "fusion-melaclear": "/images/products/cutouts/sourced/fusion-melaclear.webp",
  "arasti-white": "/images/products/cutouts/sourced/arasti-white.webp",
  "mesolike-eye-top": "/images/products/cutouts/market-reference/mesolike-eye-top.webp",
  "medicube-pdrn": "/images/products/cutouts/market-reference/medicube-pdrn.webp",
  "mesolike-hair": "/images/products/cutouts/market-reference/mesolike-hair.webp",
  "mesolike-whitening-shine": "/images/products/cutouts/market-reference/mesolike-whitening-shine.webp",
  "xitritall-hydro": "/images/products/cutouts/market-reference/xitritall-hydro.webp",
  "genosys-sws": "/images/products/cutouts/market-reference/genosys-sws.webp",
  "mesolike-dutasteride": "/images/products/cutouts/market-reference/mesolike-dutasteride.webp",
  "roytrin-skin-booster": "/images/products/cutouts/market-reference/roytrin-skin-booster.webp",
  "revitacare-532": "/images/products/cutouts/market-reference/revitacare-532.webp",
  "dermaheal-sb": "/images/products/cutouts/market-reference/dermaheal-sb.webp",
  "neuronox-reference": "/images/products/cutouts/market-reference/neuronox-reference.webp",
  "reyoungel-revital-bioha": "/images/products/cutouts/market-reference/reyoungel-revital-bioha.webp",
  "revitacare-haircare": "/images/products/cutouts/market-reference/revitacare-haircare.webp",
  "mesoheal-plus": "/images/products/cutouts/market-reference/mesoheal-plus.webp",
  "mesolike-glutathione": "/images/products/cutouts/market-reference/mesolike-glutathione.webp",
  "dermaheal-hl": "/images/products/cutouts/market-reference/dermaheal-hl.webp",
  "genosys-hr3": "/images/products/cutouts/market-reference/genosys-hr3.webp",
  "vitten-hydro-plus": "/images/products/cutouts/market-reference/vitten-hydro-plus.webp",
  "mesolike-hair-men": "/images/products/cutouts/market-reference/mesolike-hair-men.webp",
  "fusion-f-mesomatrix": "/images/products/cutouts/sourced/f-mesomatrix.webp",
  "fusion-f-lift-face": "/images/products/cutouts/sourced/fusion-lift-face.webp",
  "fusion-f-melaclear": "/images/products/cutouts/sourced/fusion-melaclear.webp",
  "fusion-f-vitamin-c": "/images/products/cutouts/sourced/f-vitamin-c.webp",
  "fusion-f-melirutin": "/images/products/cutouts/sourced/f-melirutin.webp",
  "fusion-f-eye-contour": "/images/products/cutouts/sourced/f-eye-contour.webp",
  "fusion-f-hair": "/images/products/cutouts/sourced/f-hair.webp",
  "fusion-f-hair-men": "/images/products/cutouts/sourced/fusion-hair-men.webp"
};

export function approvedLegacyCutout(sourceUrl: string): string | null {
  let filename: string;
  try { filename = decodeURIComponent(new URL(sourceUrl).pathname.split("/").pop() ?? ""); }
  catch { return null; }
  if (!filename.startsWith("sepiid-role-") || filename.includes("sepiid-cutout-")) return null;
  const slot = filename.indexOf("-slot-");
  if (slot < 0) return null;
  const stem = filename.slice(slot + 6).replace(/\.(webp|png|jpe?g)$/iu, "");
  return approvedProductCutouts[stem] ?? null;
}
