import type { ProductSeed } from "../product-seed";

const reviewedAt = "2026-08-10";
const professionalAudience = "پزشکان و مراکز دارای صلاحیت خرید و استفاده حرفه‌ای";

export const fillerInventorySeeds: ProductSeed[] = [
  {
    slug: "alcarisa-family",
    nameFa: "فیلر آلکاریسا",
    nameEn: "ALCARISA",
    brand: "Alcarisa / Spad Pharmed",
    category: "fillers",
    type: "خانواده فیلرهای یک‌میلی‌لیتری",
    volume: "هر جعبه ۲ سرنگ ۱ میلی‌لیتری",
    priceToman: 2500000,
    priceNote: "قیمت هر عدد؛ مدل را انتخاب کنید",
    badge: "۳ مدل موجود",
    image: "/images/products/alcarisa-16.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Rokateb — Alcarisa 16/20/24",
    sourceUrl: "https://rokateb.ir/product/alcarisa-24-filler/",
    reviewedAt,
    sourceStatus: "تعداد و حجم سرنگ‌ها از صفحه محصول تطبیق شد؛ عدد مدل با حجم اشتباه نشود",
    summary:
      "آلکاریسا یک خانواده سه‌مدلی در موجودی سفید بیوتی است. عددهای ۱۶، ۲۰ و ۲۴ نام مدل‌اند و حجم محصول نیستند؛ هر جعبه دو سرنگ یک‌میلی‌لیتری دارد. با انتخاب مدل، تصویر، قیمت و مشخصات همان بسته عوض می‌شود.",
    audience: professionalAudience,
    features: [
      "سه مدل ۱۶، ۲۰ و ۲۴ با صفحه ثابت و انتخاب‌گر یکپارچه",
      "حجم واقعی هر مدل: دو سرنگ یک‌میلی‌لیتری، مجموع ۲ میلی‌لیتر",
      "تولید ایران؛ نام مدل و اطلاعات روی سرنگ پیش از سفارش تطبیق داده می‌شود",
    ],
    specs: [
      ["خانواده محصول", "ALCARISA"],
      ["سازنده", "Spad Pharmed — ایران"],
      ["مدل‌های موجود", "۱۶، ۲۰ و ۲۴"],
      ["حجم هر جعبه", "۲ × ۱ میلی‌لیتر"],
      ["نکته انتخاب", "عدد مدل، حجم سرنگ نیست"],
    ],
    checks: [
      "عدد مدل روی جعبه، بلیستر و هر دو سرنگ یکسان باشد.",
      "وجود دو سرنگ یک‌میلی‌لیتری، پلمب، بچ‌کد و تاریخ همان جعبه بررسی شود.",
      "قیمت ثبت‌شده برای هر عدد است؛ تعداد در مرحله استعلام دوباره تأیید شود.",
    ],
    faq: [
      {
        question: "آلکاریسا ۱۶ یعنی ۱۶ سی‌سی؟",
        answer: "خیر. ۱۶ نام مدل است. بسته بررسی‌شده دو سرنگ یک‌میلی‌لیتری و در مجموع ۲ میلی‌لیتر دارد.",
      },
      {
        question: "چطور مدل آلکاریسا را انتخاب کنم؟",
        answer: "در همین صفحه مدل را انتخاب کنید تا مشخصات و قیمت درست را ببینید؛ تصمیم نهایی درباره تناسب مدل با کار موردنظر با فرد واجد صلاحیت است.",
      },
    ],
    variants: [
      {
        id: "16",
        label: "مدل ۱۶",
        nameFa: "آلکاریسا ۱۶",
        nameEn: "ALCARISA 16",
        image: "/images/products/alcarisa-16.webp",
        imageAlt: "بسته واقعی آلکاریسا ۱۶ با چیدمان ادیتوریال",
        imageVerified: true,
        volume: "۲ سرنگ ۱ میلی‌لیتری؛ مجموع ۲ میلی‌لیتر",
        summary: "آلکاریسا ۱۶ کم‌عددترین مدل این خانواده است. عدد ۱۶ فقط مدل را مشخص می‌کند؛ قیمت فهرست برای هر عدد و حجم جعبه دو سرنگ یک‌میلی‌لیتری است.",
        features: ["مدل ۱۶", "۲ × ۱ میلی‌لیتر", "قیمت فهرست برای هر عدد"],
        specs: [["مدل", "ALCARISA 16"], ["حجم", "۲ × ۱ میلی‌لیتر"], ["ساخت", "ایران"], ["قیمت فهرست", "هر عدد"]],
        priceToman: 2500000,
        priceNote: "هر عدد؛ موجودی همان بچ استعلام شود",
        sourceName: "Rokateb — Alcarisa 16",
        sourceUrl: "https://rokateb.ir/product/alcarisa-16-filler/",
      },
      {
        id: "20",
        label: "مدل ۲۰",
        nameFa: "آلکاریسا ۲۰",
        nameEn: "ALCARISA 20",
        image: "/images/products/alcarisa-20.webp",
        imageAlt: "بسته واقعی آلکاریسا ۲۰ با چیدمان ادیتوریال",
        imageVerified: true,
        volume: "۲ سرنگ ۱ میلی‌لیتری؛ مجموع ۲ میلی‌لیتر",
        summary: "آلکاریسا ۲۰ مدل میانی این خانواده است. حجم آن مانند مدل‌های دیگر دو سرنگ یک‌میلی‌لیتری است و عدد ۲۰ نباید به‌عنوان حجم خوانده شود.",
        features: ["مدل ۲۰", "۲ × ۱ میلی‌لیتر", "قیمت فهرست برای هر عدد"],
        specs: [["مدل", "ALCARISA 20"], ["حجم", "۲ × ۱ میلی‌لیتر"], ["ساخت", "ایران"], ["قیمت فهرست", "هر عدد"]],
        priceToman: 2400000,
        priceNote: "هر عدد؛ موجودی همان بچ استعلام شود",
        sourceName: "Rokateb — Alcarisa 20",
        sourceUrl: "https://rokateb.ir/product/alcarisa-20-filler/",
      },
      {
        id: "24",
        label: "مدل ۲۴",
        nameFa: "آلکاریسا ۲۴",
        nameEn: "ALCARISA 24",
        image: "/images/products/alcarisa-24.webp",
        imageAlt: "بسته واقعی آلکاریسا ۲۴ با چیدمان ادیتوریال",
        imageVerified: true,
        volume: "۲ سرنگ ۱ میلی‌لیتری؛ مجموع ۲ میلی‌لیتر",
        summary: "آلکاریسا ۲۴ سومین مدل موجود است. مشخصات سفارش با نام کامل ۲۴ ثبت می‌شود و هر جعبه دو سرنگ یک‌میلی‌لیتری دارد.",
        features: ["مدل ۲۴", "۲ × ۱ میلی‌لیتر", "قیمت فهرست برای هر عدد"],
        specs: [["مدل", "ALCARISA 24"], ["حجم", "۲ × ۱ میلی‌لیتر"], ["ساخت", "ایران"], ["قیمت فهرست", "هر عدد"]],
        priceToman: 2400000,
        priceNote: "هر عدد؛ موجودی همان بچ استعلام شود",
        sourceName: "Rokateb — Alcarisa 24",
        sourceUrl: "https://rokateb.ir/product/alcarisa-24-filler/",
      },
    ],
  },
  {
    slug: "revofil-ultra",
    nameFa: "رووفیل",
    nameEn: "REVOFIL",
    brand: "Revofil / Caregen",
    category: "fillers",
    type: "فیلر حرفه‌ای؛ دو بسته متفاوت بازار",
    volume: "۱ سی‌سی و ۱۰ سی‌سی",
    priceToman: 5200000,
    priceNote: "مدل و حجم بسته را انتخاب کنید",
    badge: "۲ حجم موجود",
    image: "/images/products/revofil-1ml.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Caregen REVOFIL / Torob market listing",
    sourceUrl: "https://www.caregen.com/products/aesthetic/dermal_fillers.php",
    reviewedAt,
    sourceStatus: "بسته ۱ سی‌سی با خانواده Caregen تطبیق دارد؛ نسخه ۱۰ سی‌سی فقط پس از دیدن بسته همان سفارش تأیید می‌شود",
    warning: "نسخه ۱۰ سی‌سی را معادل خودکار بسته رسمی Caregen در نظر نگیرید.",
    summary:
      "رووفیل در فهرست موجودی با دو حجم ۱ و ۱۰ سی‌سی آمده است. چون بسته ۱۰ سی‌سی با بسته‌های رایج یک‌میلی‌لیتری Caregen یکسان نیست، صفحه این تفاوت را پنهان نمی‌کند و برای آن تأیید تصویر جعبه و سازنده را قبل از سفارش لازم می‌داند.",
    audience: professionalAudience,
    features: ["انتخاب جداگانه ۱ و ۱۰ سی‌سی", "نمایش قیمت و هشدار مخصوص هر حجم", "تطبیق نام مدل و سازنده پیش از تأیید سفارش"],
    specs: [["برند", "REVOFIL"], ["سازنده مدل رسمی ۱ سی‌سی", "Caregen — کره جنوبی"], ["حجم‌های موجود", "۱ و ۱۰ سی‌سی"], ["نکته مهم", "بسته ۱۰ سی‌سی نیازمند تأیید هویت همان کالا است"]],
    checks: ["نام کامل مدل رووفیل روی جعبه و سرنگ خوانده شود.", "برای نسخه ۱۰ سی‌سی، تصویر جلو و پشت بسته و نام سازنده قبل از پرداخت دریافت شود.", "بچ‌کد، تاریخ و سلامت پلمب با همان سفارش تطبیق داده شود."],
    faq: [{ question: "رووفیل ۱۰ سی‌سی همان رووفیل یک‌سی‌سی است؟", answer: "خیر، این دو بسته را نباید خودکار یکسان دانست. نام مدل، سازنده و تصویر همان بسته ۱۰ سی‌سی باید جداگانه تأیید شود." }, { question: "قیمت کدام حجم نمایش داده می‌شود؟", answer: "با انتخاب هر گزینه، قیمت همان حجم نمایش داده می‌شود؛ قیمت ۱ سی‌سی ۵٬۲۰۰٬۰۰۰ و ۱۰ سی‌سی ۶٬۰۰۰٬۰۰۰ تومان در فهرست فعلی است." }],
    variants: [
      { id: "1ml", label: "۱ سی‌سی", nameFa: "رووفیل ۱ سی‌سی", nameEn: "REVOFIL 1 mL", image: "/images/products/revofil-1ml.webp", imageAlt: "بسته رووفیل یک میلی‌لیتری با ادیت مینیمال", imageVerified: true, volume: "۱ میلی‌لیتر", summary: "گزینه یک‌میلی‌لیتری رووفیل برای سفارش تک‌حجم ثبت شده است. مدل دقیق روی جعبه در زمان استعلام خوانده می‌شود تا با مدل‌های دیگر خانواده جابه‌جا نشود.", features: ["حجم سفارش: ۱ میلی‌لیتر", "مدل روی بسته مبنای تحویل", "قیمت مخصوص همین حجم"], specs: [["حجم", "۱ میلی‌لیتر"], ["مدل دقیق", "هنگام استعلام از روی جعبه"], ["واحد قیمت", "هر بسته"]], priceToman: 5200000, priceNote: "برای بسته ۱ سی‌سی", sourceName: "REVOFIL technical listing", sourceUrl: "https://www.directdermasupplies.com/products/revofil/revofil-ultra-1ml" },
      { id: "10ml", label: "۱۰ سی‌سی", nameFa: "رووفیل ۱۰ سی‌سی", nameEn: "REVOFIL 10 mL — market pack", image: "/images/drive/product-revofil.webp", imageAlt: "نمای واقعی خانواده رووفیل؛ بسته ده‌میلی‌لیتری هنگام استعلام تطبیق می‌شود", imageVerified: false, volume: "۱۰ میلی‌لیتر؛ طبق فهرست موجودی", summary: "این گزینه همان ردیف ۱۰ سی‌سی فهرست موجودی است. به‌دلیل تفاوت با بسته رایج Caregen، فروش تنها پس از تطبیق تصویر، نام سازنده، حجم و بچ همان کالا انجام می‌شود.", features: ["حجم فهرست: ۱۰ میلی‌لیتر", "نیازمند تأیید هویت بسته", "نباید معادل مدل ۱ سی‌سی فرض شود"], specs: [["حجم درج‌شده در فهرست", "۱۰ میلی‌لیتر"], ["سازنده و کشور این بسته", "از روی بسته فعلی تأیید شود"], ["وضعیت تطبیق", "تصویر و سازنده همان بسته لازم است"], ["واحد قیمت", "هر بسته"]], priceToman: 6000000, priceNote: "پس از تأیید تصویر همان بسته", sourceName: "Torob — Revofil 10cc market listing", sourceUrl: "https://torob.com/p/acb5268f-3102-4689-bad2-120c18710ca4/", sourceStatus: "تصویر صفحه، نمای خانواده است؛ تصویر دقیق بسته ۱۰ سی‌سی پیش از فروش دریافت می‌شود" },
    ],
  },
  {
    slug: "rabianca",
    nameFa: "رابیانکا ۷۰ سی‌سی",
    nameEn: "RABIENCA 70 mL",
    brand: "Rabienca / Quiver Medic",
    category: "fillers",
    type: "فیلر حجم بالا",
    volume: "۱ ویال ۷۰ میلی‌لیتری",
    priceToman: 16900000,
    priceNote: "هر ویال ۷۰ میلی‌لیتری",
    badge: "حجم بالا",
    image: "/images/products/rabianca-70ml.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Rabienca / Quiver Medic",
    sourceUrl: "https://www.rabianca.com/",
    reviewedAt,
    sourceStatus: "حجم ۷۰ میلی‌لیتر و سازنده با منابع برند تطبیق شد؛ املای روی بسته تحویلی مرجع نهایی است",
    summary: "رابیانکا یک محصول ۷۰ میلی‌لیتری است و با فیلتر بیشتر از ۲ میلی‌لیتر سریع‌تر پیدا می‌شود. قیمت برای یک ویال کامل ثبت شده و پیش از تحویل، نام برند، حجم، پلمب و بچ همان ویال کنترل می‌شود.",
    audience: professionalAudience,
    features: ["یک ویال ۷۰ میلی‌لیتری", "ساخت کره جنوبی توسط Quiver Medic", "قابل دسترسی با فیلتر بیشتر از ۲ میلی‌لیتر"],
    specs: [["نام لاتین روی منبع", "RABIENCA"], ["سازنده", "Quiver Medic Co., Ltd."], ["کشور سازنده", "کره جنوبی"], ["حجم", "۷۰ میلی‌لیتر"], ["واحد قیمت", "هر ویال"]],
    checks: ["املای RABIENCA و نام Quiver Medic روی بسته کنترل شود.", "حجم 70 mL، بچ‌کد، تاریخ و پلمب ویال ثبت شود.", "شرایط حمل و سلامت بسته پیش از پذیرش بررسی شود."],
    faq: [{ question: "رابیانکا واقعاً ۷۰ سی‌سی است؟", answer: "بله، منبع برند و فهرست محصول حجم ۷۰ میلی‌لیتر را نشان می‌دهند؛ حجم روی همان ویال موجود هم پیش از سفارش دوباره کنترل می‌شود." }, { question: "قیمت برای یک سی‌سی است؟", answer: "خیر. قیمت ثبت‌شده برای یک ویال ۷۰ میلی‌لیتری است." }],
  },
  {
    slug: "eptq-1ml",
    nameFa: "ای‌پی‌تی‌کیو ۱ سی‌سی",
    nameEn: "e.p.t.q. 1 mL",
    brand: "e.p.t.q. / JETEMA",
    category: "fillers",
    type: "فیلر یک‌میلی‌لیتری؛ مدل روی بسته",
    volume: "۱ میلی‌لیتر در فهرست موجودی",
    priceToman: 2600000,
    priceNote: "مدل S100/S300/S500 هنگام استعلام مشخص شود",
    image: "/images/products/eptq/eptq-s500.webp",
    imageAlt: "تصویر بسته واقعی ای‌پی‌تی‌کیو S500 یک میلی‌لیتری با چیدمان ادیتوریال",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "JETEMA — e.p.t.q. product family",
    sourceUrl: "https://www.jetema.com/eng/product/eptq",
    reviewedAt,
    sourceStatus: "خانواده و سه مدل S100، S300 و S500 با صفحه رسمی JETEMA تطبیق شد؛ مدل انتخابی از روی بسته همان گزینه نمایش داده می‌شود",
    summary: "ای‌پی‌تی‌کیو یک خانواده سه‌مدلی یک‌میلی‌لیتری است. با انتخاب S100، S300 یا S500، تصویر واقعی همان مدل، مشخصات مدل و قیمت همان گزینه در همین صفحه تغییر می‌کند.",
    audience: professionalAudience,
    features: ["سه مدل S100، S300 و S500", "هر بسته: یک سرنگ یک‌میلی‌لیتری", "ساخت JETEMA کره جنوبی"],
    specs: [["برند", "e.p.t.q."], ["سازنده", "JETEMA"], ["کشور سازنده", "کره جنوبی"], ["حجم", "۱ میلی‌لیتر"], ["مدل‌های موجود", "S100، S300 و S500"]],
    checks: ["کد مدل دقیق روی جعبه و سرنگ خوانده شود.", "حجم درج‌شده روی بسته با سفارش یک‌سی‌سی تطبیق داده شود.", "بچ‌کد، تاریخ، پلمب و اطلاعات واردکننده همان بسته بررسی شود."],
    faq: [{ question: "ای‌پی‌تی‌کیو چه مدل‌هایی دارد؟", answer: "در این صفحه مدل‌های S100، S300 و S500 به‌صورت جداگانه قابل انتخاب‌اند و تصویر و مشخصات هر مدل با انتخاب آن تغییر می‌کند." }, { question: "حجم هر مدل EPTQ چقدر است؟", answer: "هر سه مدل این خانواده در بسته یک‌میلی‌لیتری معرفی شده‌اند؛ مدل انتخاب‌شده باید با نوشته روی همان بسته تطبیق داده شود." }],
    variants: [
      {
        id: "s100",
        label: "S100 · ۱ سی‌سی",
        nameFa: "ای‌پی‌تی‌کیو S100",
        nameEn: "e.p.t.q. S100 1 mL",
        image: "/images/products/eptq/eptq-s100.webp",
        imageAlt: "تصویر بسته واقعی ای‌پی‌تی‌کیو S100 یک میلی‌لیتری با چیدمان ادیتوریال سپید بیوتی",
        imageVerified: true,
        imageKind: "official",
        volume: "۱ سرنگ ۱ میلی‌لیتری",
        summary: "مدل S100 از خانواده ای‌پی‌تی‌کیو در بسته یک‌میلی‌لیتری عرضه می‌شود. نام مدل و حجم روی بسته انتخاب‌شده مبنای استعلام است.",
        features: ["مدل S100", "۱ × ۱ میلی‌لیتر", "بسته‌بندی سفید با جزئیات سبز"],
        specs: [["مدل", "e.p.t.q. S100"], ["حجم", "۱ × ۱ میلی‌لیتر"], ["بسته", "یک سرنگ"], ["ساخت", "کره جنوبی"]],
        priceToman: 2600000,
        priceNote: "هر بسته یک‌سی‌سی؛ موجودی همان مدل استعلام شود",
        sourceName: "JETEMA — e.p.t.q. S100",
        sourceUrl: "https://www.jetema.com/page/eptq",
      },
      {
        id: "s300",
        label: "S300 · ۱ سی‌سی",
        nameFa: "ای‌پی‌تی‌کیو S300",
        nameEn: "e.p.t.q. S300 1 mL",
        image: "/images/products/eptq/eptq-s300.webp",
        imageAlt: "تصویر بسته واقعی ای‌پی‌تی‌کیو S300 یک میلی‌لیتری با چیدمان ادیتوریال سپید بیوتی",
        imageVerified: true,
        imageKind: "official",
        volume: "۱ سرنگ ۱ میلی‌لیتری",
        summary: "مدل S300 از خانواده ای‌پی‌تی‌کیو در بسته یک‌میلی‌لیتری عرضه می‌شود. مدل دقیق پیش از سفارش با نوشته روی همان بسته تطبیق داده می‌شود.",
        features: ["مدل S300", "۱ × ۱ میلی‌لیتر", "بسته‌بندی سفید با جزئیات نارنجی"],
        specs: [["مدل", "e.p.t.q. S300"], ["حجم", "۱ × ۱ میلی‌لیتر"], ["بسته", "یک سرنگ"], ["ساخت", "کره جنوبی"]],
        priceToman: 2600000,
        priceNote: "هر بسته یک‌سی‌سی؛ موجودی همان مدل استعلام شود",
        sourceName: "JETEMA — e.p.t.q. S300",
        sourceUrl: "https://www.jetema.com/page/eptq",
      },
      {
        id: "s500",
        label: "S500 · ۱ سی‌سی",
        nameFa: "ای‌پی‌تی‌کیو S500",
        nameEn: "e.p.t.q. S500 1 mL",
        image: "/images/products/eptq/eptq-s500.webp",
        imageAlt: "تصویر بسته واقعی ای‌پی‌تی‌کیو S500 یک میلی‌لیتری با چیدمان ادیتوریال سپید بیوتی",
        imageVerified: true,
        imageKind: "official",
        volume: "۱ سرنگ ۱ میلی‌لیتری",
        summary: "مدل S500 از خانواده ای‌پی‌تی‌کیو در بسته یک‌میلی‌لیتری عرضه می‌شود. نوشته S500 و حجم روی بسته انتخاب‌شده باید با سفارش تطبیق داشته باشد.",
        features: ["مدل S500", "۱ × ۱ میلی‌لیتر", "بسته‌بندی سفید با جزئیات آبی"],
        specs: [["مدل", "e.p.t.q. S500"], ["حجم", "۱ × ۱ میلی‌لیتر"], ["بسته", "یک سرنگ"], ["ساخت", "کره جنوبی"]],
        priceToman: 2600000,
        priceNote: "هر بسته یک‌سی‌سی؛ موجودی همان مدل استعلام شود",
        sourceName: "JETEMA — e.p.t.q. S500",
        sourceUrl: "https://www.jetema.com/page/eptq",
      },
    ],
  },
  {
    slug: "neuramis-deep-lidocaine",
    nameFa: "نورامیس",
    nameEn: "NEURAMIS",
    brand: "Neuramis / Medytox",
    category: "fillers",
    type: "خانواده فیلر نورامیس",
    volume: "مدل‌های ۱ میلی‌لیتری و بسته‌های ۱۰ × ۱ میلی‌لیتری",
    priceToman: 2600000,
    priceNote: "حجم و مدل را انتخاب کنید",
    badge: "۴ انتخاب موجود",
    image: "/images/products/neuramis-deep-1ml.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Medytox — NEURAMIS",
    sourceUrl: "https://www.medytox.com/page/neuramis_en?site_id=en",
    reviewedAt,
    sourceStatus: "واحد رسمی 1.0 mL با Medytox تطبیق شد؛ گزینه‌های ۱۰ میلی‌لیتری به‌صورت بسته ۱۰ عددی نمایش داده می‌شوند",
    warning: "گزینه ۱۰ میلی‌لیتری یک سرنگ ۱۰ میل نیست؛ مجموع ۱۰ سرنگ یک‌میلی‌لیتری است.",
    summary: "نورامیس در موجودی با مدل‌های تک‌سی‌سی Deep و Volume و دو بسته چندتایی Deep و Lido عرضه می‌شود. گزینه‌های ۱۰ میلی‌لیتری به‌صورت ۱۰ سرنگ یک‌میلی‌لیتری نمایش داده می‌شوند تا با یک سرنگ ساختگی ۱۰ میلی‌لیتری اشتباه نشوند.",
    audience: professionalAudience,
    features: ["Deep و Volume در حجم ۱ میلی‌لیتر", "Deep و Lido در بسته ۱۰ × ۱ میلی‌لیتری", "قیمت جداگانه برای تک‌واحد و بسته ۱۰ عددی"],
    specs: [["برند", "NEURAMIS"], ["سازنده مدل‌های رسمی", "Medytox — کره جنوبی"], ["انتخاب‌ها", "Deep 1mL، Volume 1mL، Deep 10×1mL، Lido 10×1mL"]],
    checks: ["نام مدل روی جعبه و سرنگ با گزینه انتخاب‌شده یکسان باشد.", "برای بسته ۱۰ عددی، تعداد ۱۰ سرنگ 1.0 mL روی فاکتور و بسته تأیید شود.", "بچ‌کد، تاریخ، پلمب و شرایط نگهداری همان بسته کنترل شود."],
    faq: [{ question: "نورامیس ۱ سی‌سی چه مدل‌هایی دارد؟", answer: "در موجودی فعلی Deep و Volume با قیمت یکسان ثبت شده‌اند؛ مشخصات هر کدام با انتخاب مدل نمایش داده می‌شود." }, { question: "نورامیس ۱۰ میل یک سرنگ است؟", answer: "خیر. در این صفحه ۱۰ میل به‌صورت بسته ۱۰ عددیِ سرنگ‌های یک‌میلی‌لیتری نمایش داده می‌شود؛ واحد رسمی معرفی‌شده توسط Medytox برای هر سرنگ 1.0 mL است." }],
    variants: [
      { id: "deep-1ml", label: "Deep · ۱ سی‌سی", nameFa: "نورامیس دیپ ۱ سی‌سی", nameEn: "NEURAMIS Deep 1 mL", image: "/images/products/neuramis-deep-1ml.webp", imageAlt: "بسته نورامیس دیپ یک میلی‌لیتری با ادیت مینیمال", imageVerified: true, volume: "۱ سرنگ ۱ میلی‌لیتری", summary: "نورامیس Deep یک‌میلی‌لیتری از مدل‌های رسمی خانواده Medytox است. نام Deep و حجم 1.0 mL روی جعبه و سرنگ مبنای تحویل است.", features: ["مدل Deep", "۱ × ۱ میلی‌لیتر", "بسته رسمی خانواده Medytox"], specs: [["مدل", "NEURAMIS Deep"], ["حجم", "۱ × ۱ میلی‌لیتر"], ["سازنده", "Medytox"]], priceToman: 2600000, priceNote: "هر بسته یک‌سی‌سی", sourceName: "Medytox — NEURAMIS", sourceUrl: "https://www.medytox.com/page/neuramis_en?site_id=en" },
      { id: "volume-1ml", label: "Volume · ۱ سی‌سی", nameFa: "نورامیس والیوم ۱ سی‌سی", nameEn: "NEURAMIS Volume 1 mL", image: "/images/products/neuramis-volume-1ml.webp", imageAlt: "بسته نورامیس والیوم یک میلی‌لیتری با ادیت مینیمال", imageVerified: true, volume: "۱ سرنگ ۱ میلی‌لیتری", summary: "نورامیس Volume گزینه یک‌میلی‌لیتری این خانواده است. برای تحویل، عبارت Volume و حجم 1.0 mL باید روی همه اجزای بسته یکسان باشد.", features: ["مدل Volume", "۱ × ۱ میلی‌لیتر", "قیمت همان ردیف یک‌سی‌سی"], specs: [["مدل", "NEURAMIS Volume"], ["حجم", "۱ × ۱ میلی‌لیتر"], ["سازنده", "Medytox"]], priceToman: 2600000, priceNote: "هر بسته یک‌سی‌سی", sourceName: "Medytox — NEURAMIS", sourceUrl: "https://www.medytox.com/page/neuramis_en?site_id=en" },
      { id: "deep-10ml", label: "Deep · ۱۰×۱ میل", nameFa: "نورامیس دیپ بسته ۱۰ عددی", nameEn: "NEURAMIS Deep 10 × 1 mL", image: "/images/products/neuramis-deep-10-pack.webp", imageAlt: "تصویر ادیتوریال بسته نورامیس دیپ با نشان ۱۰ سرنگ یک‌میلی‌لیتری و مجموع ۱۰ میلی‌لیتر", imageVerified: false, imageKind: "editorial-family", imageApproved: true, volume: "۱۰ × ۱ میلی‌لیتر؛ مجموع ۱۰ میلی‌لیتر", summary: "این انتخاب برای بسته چندتایی نورامیس Deep است: ۱۰ سرنگ یک‌میلی‌لیتری با مجموع ۱۰ میلی‌لیتر. تصویر، ادیت گرافیکی شفاف از جعبه واقعی Deep است و نشان حجم برای تشخیص سریع بسته به آن افزوده شده است.", features: ["۱۰ سرنگ یک‌میلی‌لیتری", "مجموع ۱۰ میلی‌لیتر", "تصویر ادیتوریال مبتنی بر جعبه واقعی Deep"], specs: [["مدل", "NEURAMIS Deep"], ["چیدمان حجم", "۱۰ × ۱ میلی‌لیتر"], ["حجم مجموع", "۱۰ میلی‌لیتر"], ["سازنده هر واحد", "Medytox — کره جنوبی"]], priceToman: 6000000, priceNote: "برای بسته ۱۰ عددی", sourceName: "Medytox + فهرست بازار ترب", sourceUrl: "https://torob.com/p/f5620461-ac1d-4547-a737-7ab523432bef/", sourceStatus: "واحد رسمی هر سرنگ 1.0 mL است؛ تصویر ۱۰×۱ میل ادیت گرافیکی فروشگاهی است" },
      { id: "lido-10ml", label: "Lido · ۱۰×۱ میل", nameFa: "نورامیس لیدو بسته ۱۰ عددی", nameEn: "NEURAMIS Lido 10 × 1 mL", image: "/images/products/neuramis-lido-10-pack.webp", imageAlt: "تصویر ادیتوریال بسته نورامیس لیدوکائین با نشان ۱۰ سرنگ یک‌میلی‌لیتری و مجموع ۱۰ میلی‌لیتر", imageVerified: false, imageKind: "editorial-family", imageApproved: true, volume: "۱۰ × ۱ میلی‌لیتر؛ مجموع ۱۰ میلی‌لیتر", summary: "این انتخاب برای بسته چندتایی نورامیس Lido است: ۱۰ سرنگ یک‌میلی‌لیتری با مجموع ۱۰ میلی‌لیتر. تصویر از جعبه واقعی Lido ساخته شده و نشان حجم ادیتوریال برای تفکیک این بسته از گزینه تک‌سی‌سی روی آن قرار گرفته است.", features: ["۱۰ سرنگ یک‌میلی‌لیتری", "مجموع ۱۰ میلی‌لیتر", "تصویر ادیتوریال مبتنی بر جعبه واقعی Lido"], specs: [["مدل", "NEURAMIS Lido"], ["چیدمان حجم", "۱۰ × ۱ میلی‌لیتر"], ["حجم مجموع", "۱۰ میلی‌لیتر"], ["سازنده هر واحد", "Medytox — کره جنوبی"]], priceToman: 6000000, priceNote: "برای بسته ۱۰ عددی", sourceName: "Medytox + فهرست بازار ترب", sourceUrl: "https://torob.com/p/f5620461-ac1d-4547-a737-7ab523432bef/", sourceStatus: "واحد رسمی هر سرنگ 1.0 mL است؛ تصویر ۱۰×۱ میل ادیت گرافیکی فروشگاهی است" },
    ],
  },
  {
    slug: "hyamax-contour",
    nameFa: "هایامکس کانتور",
    nameEn: "HYAMAX Contour",
    brand: "HYAMAX",
    category: "fillers",
    type: "فیلر حجم بالا",
    volume: "۱ سرنگ ۱۰ میلی‌لیتری",
    priceToman: 6200000,
    priceNote: "هر سرنگ ۱۰ میلی‌لیتری",
    image: "/images/products/hyamax-contour.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "HYAMAX / technical listing",
    sourceUrl: "https://www.hyamax.com/",
    reviewedAt,
    sourceStatus: "نام Contour و حجم ۱ × ۱۰ میلی‌لیتر با فهرست‌های فنی تطبیق شد",
    summary: "هایامکس کانتور یک سرنگ ۱۰ میلی‌لیتری است و در فیلتر فیلرهای بیشتر از ۲ میلی‌لیتر نمایش داده می‌شود. قیمت برای همان سرنگ کامل ثبت شده؛ پیش از سفارش، عبارت Contour و حجم روی جعبه با تصویر موجودی تطبیق داده می‌شود.",
    audience: professionalAudience,
    features: ["یک سرنگ از پیش پرشده ۱۰ میلی‌لیتری", "مدل مشخص Contour", "قیمت برای یک بسته کامل"],
    specs: [["مدل", "HYAMAX Contour"], ["سازنده", "Laboratories Hyamed SA"], ["کشور سازنده", "سوئیس"], ["حجم", "۱ × ۱۰ میلی‌لیتر"], ["واحد قیمت", "هر بسته"]],
    checks: ["عبارت Contour و 10 mL روی جعبه و سرنگ یکسان باشد.", "نام سازنده، بچ‌کد و تاریخ روی همان بسته خوانا باشد.", "پلمب و سلامت سرنگ پیش از تحویل بررسی شود."],
    faq: [{ question: "هایامکس کانتور چند سی‌سی است؟", answer: "بسته بررسی‌شده یک سرنگ ۱۰ میلی‌لیتری دارد." }, { question: "قیمت برای چند سرنگ است؟", answer: "قیمت ثبت‌شده برای یک بسته شامل یک سرنگ ۱۰ میلی‌لیتری است." }],
  },
  {
    slug: "cg-dimono-ptx",
    nameFa: "سی‌جی دیمونو پی‌تی‌ایکس",
    nameEn: "CG DIMONO PTx",
    brand: "CG Dimono / Caregen",
    category: "skin-boosters",
    type: "بسته دو سرنگی مراقبت حرفه‌ای پوست",
    volume: "۱ سرنگ ۱ میلی‌لیتری + ۱ سرنگ ۲ میلی‌لیتری",
    priceToman: 7900000,
    priceNote: "مجموع ۳ میلی‌لیتر",
    image: "/images/products/cg-dimono-ptx.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "CG Dimono PTx technical listing",
    sourceUrl: "https://moryskin.com/en/product/cg-dimono-ptx-1-x-1-ml-1-x-2-ml/",
    reviewedAt,
    sourceStatus: "ساختار دو سرنگی و مجموع حجم با فهرست فنی تطبیق شد",
    summary: "سی‌جی دیمونو PTx یک بسته دو‌سرنگی است: یک سرنگ یک‌میلی‌لیتری و یک سرنگ دو‌میلی‌لیتری. بنابراین حجم کل بسته ۳ میلی‌لیتر است و قیمت برای مجموعه کامل، نه یک سرنگ جداگانه، نمایش داده می‌شود.",
    audience: professionalAudience,
    features: ["دو سرنگ با حجم‌های متفاوت", "مجموع حجم بسته: ۳ میلی‌لیتر", "برند Caregen کره جنوبی"],
    specs: [["نام", "CG DIMONO PTx"], ["محتویات", "۱ × ۱ mL + ۱ × ۲ mL"], ["حجم کل", "۳ میلی‌لیتر"], ["سازنده", "Caregen"], ["کشور سازنده", "کره جنوبی"]],
    checks: ["هر دو سرنگ ۱ و ۲ میلی‌لیتری داخل بسته موجود باشد.", "نام PTx، بچ‌کد و تاریخ روی اجزای بسته تطبیق داده شود.", "قیمت و سفارش برای مجموعه کامل ثبت شود."],
    faq: [{ question: "دیمونو چند میل است؟", answer: "مجموع بسته ۳ میلی‌لیتر است: یک سرنگ ۱ میلی‌لیتری و یک سرنگ ۲ میلی‌لیتری." }, { question: "قیمت برای یک سرنگ است؟", answer: "خیر. قیمت برای بسته کامل دو‌سرنگی ثبت شده است." }],
  },
  {
    slug: "luxiva-mesogel",
    nameFa: "لوکسیوا",
    nameEn: "LUXIVA",
    brand: "Luxiva / Atra Zist Aray",
    category: "skin-boosters",
    type: "محلول حرفه‌ای پوست در ویال",
    volume: "هر ویال ۴ میلی‌لیتر؛ جعبه ۴ عددی، مجموع ۱۶ میلی‌لیتر",
    priceToman: 1490000,
    priceNote: "قیمت هر ویال؛ جعبه کامل ۴ ویال دارد",
    image: "/images/products/luxiva.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Atra Zist Aray / market packaging",
    sourceUrl: "https://iranadfair.com/ad/%D8%A2%D8%AA%D8%B1%D8%A7-%D8%B2%DB%8C%D8%B3%D8%AA-%D8%A2%D8%B1%D8%A7%DB%8C/",
    reviewedAt,
    sourceStatus: "قیمت فهرست برای هر عدد تفسیر شده؛ تعداد نهایی هنگام سفارش تأیید می‌شود",
    summary: "لوکسیوا در جعبه چهار‌ویالی دیده می‌شود؛ هر ویال ۴ میلی‌لیتر و مجموع جعبه ۱۶ میلی‌لیتر است. چون فهرست قیمت عبارت «هر عدد» دارد، مبلغ نمایش‌داده‌شده برای یک ویال است و قیمت جعبه کامل جداگانه استعلام می‌شود.",
    audience: professionalAudience,
    features: ["هر ویال ۴ میلی‌لیتر", "جعبه کامل ۴ ویال؛ مجموع ۱۶ میلی‌لیتر", "قیمت فهرست برای هر ویال"],
    specs: [["نام", "LUXIVA"], ["سازنده", "Atra Zist Aray"], ["کشور سازنده", "ایران"], ["حجم هر ویال", "۴ میلی‌لیتر"], ["تعداد جعبه", "۴ ویال"], ["حجم کل جعبه", "۱۶ میلی‌لیتر"], ["واحد قیمت", "هر ویال"]],
    checks: ["تعداد درخواستی به‌صورت ویال یا جعبه کامل روشن ثبت شود.", "حجم 4 mL روی هر ویال و تعداد ۴ عدد روی جعبه بررسی شود.", "بچ‌کد، تاریخ و سلامت ویال‌ها کنترل شود."],
    faq: [{ question: "لوکسیوا ۱۶ سی‌سی است یا ۴ سی‌سی؟", answer: "هر ویال ۴ میلی‌لیتر است و جعبه چهار ویال دارد؛ بنابراین مجموع جعبه ۱۶ میلی‌لیتر می‌شود." }, { question: "قیمت ۱٬۴۹۰٬۰۰۰ تومان برای جعبه کامل است؟", answer: "طبق عبارت «هر عدد» در فهرست، قیمت برای یک ویال ثبت شده است؛ قیمت جعبه کامل هنگام استعلام اعلام می‌شود." }],
  },
  {
    slug: "perleux",
    nameFa: "پرلوکس",
    nameEn: "PERLEUX",
    brand: "Perleux / NikTebCo",
    category: "skin-boosters",
    type: "مزوژل دو‌سرنگی",
    volume: "۲ سرنگ ۱ میلی‌لیتری؛ مجموع ۲ میلی‌لیتر",
    priceToman: 5300000,
    priceNote: "هر بسته دو‌سرنگی",
    image: "/images/products/perleux.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "NikTebCo — Perleux",
    sourceUrl: "https://nikmedco.com/%DA%98%D9%84-%D9%BE%D8%B1%D9%84%D9%88%DA%A9%D8%B3-perleux/",
    reviewedAt,
    sourceStatus: "تعداد و حجم سرنگ‌ها با صفحه معرفی محصول تطبیق شد",
    summary: "پرلوکس یک بسته دو‌سرنگی است و هر سرنگ یک میلی‌لیتر دارد. حجم کل ۲ میلی‌لیتر و قیمت برای جعبه کامل ثبت شده است؛ تعداد سرنگ‌ها و مشخصات روی هر دو بلیستر قبل از تحویل بررسی می‌شود.",
    audience: professionalAudience,
    features: ["۲ سرنگ یک‌میلی‌لیتری", "مجموع حجم: ۲ میلی‌لیتر", "تولید ایران توسط NikTebCo"],
    specs: [["نام", "PERLEUX"], ["سازنده", "NikTebCo"], ["کشور سازنده", "ایران"], ["تعداد", "۲ سرنگ"], ["حجم هر سرنگ", "۱ میلی‌لیتر"], ["حجم کل", "۲ میلی‌لیتر"]],
    checks: ["دو سرنگ یک‌میلی‌لیتری در جعبه وجود داشته باشد.", "نام PERLEUX، بچ‌کد و تاریخ روی جعبه و بلیسترها تطبیق داده شود.", "پلمب و سلامت هر دو سرنگ بررسی شود."],
    faq: [{ question: "پرلوکس چند سی‌سی است؟", answer: "بسته شامل دو سرنگ یک‌میلی‌لیتری و در مجموع ۲ میلی‌لیتر است." }, { question: "قیمت برای یک سرنگ است؟", answer: "خیر، قیمت برای بسته کامل دو‌سرنگی ثبت شده است." }],
  },
  {
    slug: "audrey-m",
    nameFa: "آدری",
    nameEn: "AUDREY",
    brand: "Audrey",
    category: "fillers",
    type: "خانواده فیلرهای بیشتر از ۲ میلی‌لیتر",
    volume: "هر مدل ۱ سرنگ ۱۰ میلی‌لیتری",
    priceToman: 5400000,
    priceNote: "مدل M یا H را انتخاب کنید",
    badge: "۲ مدل موجود",
    image: "/images/products/audrey-m.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Torob — Audrey M/H 10 mL",
    sourceUrl: "https://torob.com/p/bdba1a9e-d7b5-42b3-aecf-460f3a506af7/",
    reviewedAt,
    sourceStatus: "حجم ۱۰ میلی‌لیتر برای هر دو مدل در فهرست بازار تطبیق شد؛ بسته موجود مرجع نهایی است",
    summary: "آدری در دو مدل M و H موجود است. هر دو گزینه یک سرنگ ۱۰ میلی‌لیتری و قیمت یکسان دارند، اما نام مدل باید دقیق انتخاب شود؛ با تغییر مدل، عکس و مشخصات همان جعبه نمایش داده می‌شود.",
    audience: professionalAudience,
    features: ["دو مدل مستقل M و H", "هر مدل یک سرنگ ۱۰ میلی‌لیتری", "قیمت یکسان برای هر بسته"],
    specs: [["برند", "AUDREY"], ["سازنده درج‌شده", "Ostin Bio Co., Ltd."], ["کشور سازنده", "کره جنوبی"], ["مدل‌ها", "M و H"], ["حجم هر مدل", "۱ × ۱۰ میلی‌لیتر"]],
    checks: ["حرف M یا H روی جعبه و سرنگ با سفارش یکسان باشد.", "حجم 10 mL، بچ‌کد و تاریخ خوانا باشد.", "پلمب و مشخصات سازنده همان بسته بررسی شود."],
    faq: [{ question: "آدری M و H هر دو چند سی‌سی هستند؟", answer: "هر دو مدل در فهرست بررسی‌شده یک سرنگ ۱۰ میلی‌لیتری دارند." }, { question: "قیمت مدل H فرق دارد؟", answer: "در فهرست فعلی هر دو مدل ۵٬۴۰۰٬۰۰۰ تومان ثبت شده‌اند." }],
    variants: [
      { id: "m", label: "مدل M", nameFa: "آدری M", nameEn: "AUDREY M", image: "/images/products/audrey-m.webp", imageAlt: "بسته آدری M ده میلی‌لیتری با ادیت مینیمال", imageVerified: true, volume: "۱ سرنگ ۱۰ میلی‌لیتری", summary: "آدری M گزینه آبی‌رنگ خانواده آدری است. حرف M و حجم 10 mL باید روی جعبه و سرنگ تحویلی یکسان باشد.", features: ["مدل M", "۱ × ۱۰ میلی‌لیتر", "قیمت برای یک بسته"], specs: [["مدل", "AUDREY M"], ["حجم", "۱۰ میلی‌لیتر"], ["واحد قیمت", "هر بسته"]], priceToman: 5400000, priceNote: "هر بسته ۱۰ میلی‌لیتری", sourceName: "Torob — Audrey M", sourceUrl: "https://torob.com/p/bdba1a9e-d7b5-42b3-aecf-460f3a506af7/" },
      { id: "h", label: "مدل H", nameFa: "آدری H", nameEn: "AUDREY H", image: "/images/products/audrey-h.webp", imageAlt: "بسته آدری H ده میلی‌لیتری با ادیت مینیمال", imageVerified: true, volume: "۱ سرنگ ۱۰ میلی‌لیتری", summary: "آدری H گزینه تیره‌رنگ خانواده آدری است. حرف H و حجم 10 mL روی همان بسته، معیار تحویل این انتخاب است.", features: ["مدل H", "۱ × ۱۰ میلی‌لیتر", "قیمت برای یک بسته"], specs: [["مدل", "AUDREY H"], ["حجم", "۱۰ میلی‌لیتر"], ["واحد قیمت", "هر بسته"]], priceToman: 5400000, priceNote: "هر بسته ۱۰ میلی‌لیتری", sourceName: "Torob — Audrey H", sourceUrl: "https://torob.com/p/21c1f303-517e-48c6-902b-28cc48527338/" },
    ],
  },
  {
    slug: "inovosense-family",
    nameFa: "اینووسنس",
    nameEn: "INOVOSENSE",
    brand: "Inovosense",
    category: "fillers",
    type: "خانواده فیلرهای دو‌سرنگی",
    volume: "هر مدل ۲ سرنگ ۱ میلی‌لیتری",
    priceToman: 6500000,
    priceNote: "Smile، Style یا Shape را انتخاب کنید",
    badge: "۳ مدل موجود",
    image: "/images/products/inovosense-smile.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "INOVOSENSE official product pages",
    sourceUrl: "https://inovosense.com/en/products/",
    reviewedAt,
    sourceStatus: "نام، غلظت و ساختار بسته هر سه مدل با صفحات سازنده تطبیق شد",
    summary: "اینووسنس در سه مدل Smile، Style و Shape موجود است. هر مدل دو سرنگ یک‌میلی‌لیتری دارد، اما غلظت درج‌شده و قیمتشان فرق می‌کند؛ انتخاب مدل تمام اطلاعات صفحه را بدون تغییر چیدمان به‌روزرسانی می‌کند.",
    audience: professionalAudience,
    features: ["Smile با ۲۰، Style با ۲۳ و Shape با ۲۵ میلی‌گرم در میلی‌لیتر", "هر مدل ۲ × ۱ میلی‌لیتر", "سه قیمت جدا برای سه مدل"],
    specs: [["برند", "INOVOSENSE"], ["کشور سازنده", "ایران"], ["مدل‌ها", "Smile، Style، Shape"], ["حجم هر مدل", "۲ × ۱ میلی‌لیتر"]],
    checks: ["نوار رنگی و نام Smile، Style یا Shape با سفارش یکسان باشد.", "دو سرنگ یک‌میلی‌لیتری و غلظت درج‌شده کنترل شود.", "بچ‌کد، تاریخ و پلمب هر دو بلیستر بررسی شود."],
    faq: [{ question: "مدل‌های اینووسنس چه تفاوتی در این صفحه دارند؟", answer: "نام مدل، رنگ بسته، غلظت درج‌شده و قیمت متفاوت است؛ هر سه بسته دو سرنگ یک‌میلی‌لیتری دارند." }, { question: "با انتخاب مدل، صفحه عوض می‌شود؟", answer: "چیدمان ثابت می‌ماند؛ فقط عکس، نام، توضیح، قیمت و جدول مشخصات همان مدل به‌روزرسانی می‌شود." }],
    variants: [
      { id: "smile", label: "Smile", nameFa: "اینووسنس اسمایل", nameEn: "INOVOSENSE Smile", image: "/images/products/inovosense-smile.webp", imageAlt: "بسته اینووسنس اسمایل با ادیت مینیمال", imageVerified: true, volume: "۲ سرنگ ۱ میلی‌لیتری", summary: "Smile مدل ۲۰ میلی‌گرم در میلی‌لیتر خانواده اینووسنس است. بسته دو سرنگ یک‌میلی‌لیتری دارد و با نوار قرمز Smile شناخته می‌شود.", features: ["مدل Smile", "۲۰ میلی‌گرم در میلی‌لیتر", "۲ × ۱ میلی‌لیتر"], specs: [["مدل", "Smile"], ["غلظت درج‌شده", "۲۰ mg/mL"], ["حجم", "۲ × ۱ mL"]], priceToman: 6500000, priceNote: "هر بسته Smile", sourceName: "INOVOSENSE — Smile", sourceUrl: "https://inovosense.com/en/product/smile/" },
      { id: "style", label: "Style", nameFa: "اینووسنس استایل", nameEn: "INOVOSENSE Style", image: "/images/products/inovosense-style.webp", imageAlt: "بسته اینووسنس استایل با ادیت مینیمال", imageVerified: true, volume: "۲ سرنگ ۱ میلی‌لیتری", summary: "Style مدل ۲۳ میلی‌گرم در میلی‌لیتر خانواده اینووسنس است. نام Style و رنگ ویژه همین مدل باید روی جعبه و هر دو سرنگ دیده شود.", features: ["مدل Style", "۲۳ میلی‌گرم در میلی‌لیتر", "۲ × ۱ میلی‌لیتر"], specs: [["مدل", "Style"], ["غلظت درج‌شده", "۲۳ mg/mL"], ["حجم", "۲ × ۱ mL"]], priceToman: 6600000, priceNote: "هر بسته Style", sourceName: "INOVOSENSE — Style", sourceUrl: "https://inovosense.com/en/product/style/" },
      { id: "shape", label: "Shape", nameFa: "اینووسنس شیپ", nameEn: "INOVOSENSE Shape", image: "/images/products/inovosense-shape.webp", imageAlt: "بسته اینووسنس شیپ با ادیت مینیمال", imageVerified: true, volume: "۲ سرنگ ۱ میلی‌لیتری", summary: "Shape مدل ۲۵ میلی‌گرم در میلی‌لیتر خانواده اینووسنس است. بسته دو سرنگ یک‌میلی‌لیتری دارد و قیمتش جدا از Smile و Style نمایش داده می‌شود.", features: ["مدل Shape", "۲۵ میلی‌گرم در میلی‌لیتر", "۲ × ۱ میلی‌لیتر"], specs: [["مدل", "Shape"], ["غلظت درج‌شده", "۲۵ mg/mL"], ["حجم", "۲ × ۱ mL"]], priceToman: 6850000, priceNote: "هر بسته Shape", sourceName: "INOVOSENSE — Shape", sourceUrl: "https://inovosense.com/en/product/shape/" },
    ],
  },
];
