import type { ProductSeed } from "../product-seed";

const reviewedAt = "2026-08-10";
const professionalAudience = "پزشکان و مراکز دارای صلاحیت خرید و استفاده حرفه‌ای";

export const skinAndSupportInventorySeeds: ProductSeed[] = [
  {
    slug: "dr-cyj-hair-filler",
    nameFa: "هیر فیلر دکتر سی‌وای‌جی",
    nameEn: "DR.CYJ Hair Filler",
    brand: "Dr.CYJ / Caregen",
    category: "hair-cocktails",
    type: "هیر فیلر حرفه‌ای در سرنگ آماده",
    volume: "۲ سرنگ ۱ میلی‌لیتری؛ مجموع ۲ میلی‌لیتر",
    priceToman: 4600000,
    priceNote: "هر بسته دو‌سرنگی",
    image: "/images/products/dr-cyj-hair-filler.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Caregen DR.CYJ / registered product listing",
    sourceUrl: "https://www.caregen.com/products/aesthetic/hair_filler.php",
    reviewedAt,
    sourceStatus: "نام محصول و حجم بسته دو‌سرنگی با فهرست‌های ثبت و عرضه حرفه‌ای تطبیق شد",
    summary:
      "هیر فیلر دکتر CYJ محصول Caregen برای کار حرفه‌ای روی پوست سر است. بسته رایج دو سرنگ یک‌میلی‌لیتری دارد؛ بنابراین قیمت برای مجموع ۲ میلی‌لیتر ثبت شده و با ویال‌های مزوتراپی معمولی یکی در نظر گرفته نمی‌شود.",
    audience: professionalAudience,
    features: ["۲ سرنگ آماده یک‌میلی‌لیتری", "مجموع حجم بسته: ۲ میلی‌لیتر", "محصول Caregen برای استفاده حرفه‌ای روی پوست سر"],
    specs: [["نام", "DR.CYJ Hair Filler"], ["سازنده", "Caregen Co., Ltd."], ["کشور سازنده", "کره جنوبی"], ["بسته", "۲ × ۱ میلی‌لیتر"], ["شکل محصول", "سرنگ از پیش پرشده"]],
    checks: ["دو سرنگ یک‌میلی‌لیتری و نام DR.CYJ روی جعبه کنترل شود.", "بچ‌کد، تاریخ و سلامت بلیستر هر دو سرنگ بررسی شود.", "برای ریزش مو ابتدا علت توسط فرد واجد صلاحیت بررسی شود؛ نام محصول جای تشخیص را نمی‌گیرد."],
    faq: [{ question: "هیر فیلر دکتر CYJ چند سی‌سی است؟", answer: "بسته رایج شامل دو سرنگ یک‌میلی‌لیتری و در مجموع ۲ میلی‌لیتر است." }, { question: "این همان کوکتل موی ویالی است؟", answer: "خیر. این محصول به‌صورت سرنگ از پیش پرشده عرضه می‌شود و باید با نام کامل DR.CYJ سفارش داده شود." }],
  },
  {
    slug: "hyaron",
    nameFa: "هایارون",
    nameEn: "HYARON Prefilled Inj.",
    brand: "Hyaron / Dongkook",
    category: "skin-boosters",
    type: "سرنگ آماده سدیم هیالورونات",
    volume: "هر سرنگ ۲٫۵ میلی‌لیتر؛ جعبه ۱۰ سرنگی",
    priceToman: 900000,
    priceNote: "قیمت هر سرنگ ۲٫۵ میلی‌لیتری",
    image: "/images/products/hyaron.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Dongkook Pharmaceutical — Hyaron",
    sourceUrl: "https://www.dkpharm.co.kr/en/product/view.php?idx=42",
    reviewedAt,
    sourceStatus: "حجم هر سرنگ و بسته ۵ یا ۱۰ عددی با صفحه سازنده تطبیق شد؛ موجودی سفید بیوتی به‌صورت هر سرنگ قیمت‌گذاری شده است",
    summary:
      "هایارون به‌صورت سرنگ‌های آماده ۲٫۵ میلی‌لیتری عرضه می‌شود و جعبه بازار معمولاً ۱۰ سرنگ دارد. مبلغ فهرست برای یک سرنگ ثبت شده است؛ هنگام سفارش باید تعداد سرنگ، وضعیت جعبه بازشده یا کامل و تاریخ همان بسته روشن باشد.",
    audience: professionalAudience,
    features: ["هر سرنگ ۲٫۵ میلی‌لیتر", "بسته رایج ۱۰ سرنگی", "قیمت فهرست برای یک سرنگ"],
    specs: [["نام", "Hyaron Prefilled Injection"], ["سازنده", "Dongkook Pharmaceutical"], ["کشور سازنده", "کره جنوبی"], ["حجم هر سرنگ", "۲٫۵ میلی‌لیتر"], ["بسته رایج", "۱۰ سرنگ"], ["واحد قیمت", "هر سرنگ"]],
    checks: ["تعداد درخواستی به‌صورت سرنگ یا جعبه کامل ثبت شود.", "حجم 2.5 mL و نام Dongkook روی جعبه و بلیستر تطبیق داده شود.", "بچ‌کد، تاریخ و سلامت بلیستر سرنگ بررسی شود."],
    faq: [{ question: "هایارون چند میل است؟", answer: "هر سرنگ ۲٫۵ میلی‌لیتر است؛ جعبه رایج ۱۰ سرنگ دارد." }, { question: "قیمت ۹۰۰ هزار تومان برای جعبه است؟", answer: "خیر. بر اساس فهرست موجودی، قیمت برای هر سرنگ ۲٫۵ میلی‌لیتری ثبت شده است." }],
  },
  {
    slug: "kiara-reju",
    nameFa: "کیارا ریجو",
    nameEn: "KIARA REJU",
    brand: "Kiara Reju / BioPlus",
    category: "skin-boosters",
    type: "اسکین‌بوستر سه‌سرنگی",
    volume: "۳ سرنگ ۲٫۲ میلی‌لیتری؛ مجموع ۶٫۶ میلی‌لیتر",
    priceToman: 2750000,
    priceNote: "قیمت هر سرنگ؛ بسته کامل ۳ سرنگ دارد",
    image: "/images/products/kiara-reju.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Kiara Reju product specification",
    sourceUrl: "https://www.eleglobals.com/product/kiara-reju/",
    reviewedAt,
    sourceStatus: "حجم ۲٫۲ میلی‌لیتر و تعداد سه سرنگ با بسته محصول تطبیق شد؛ واحد قیمت از فهرست موجودی به‌صورت هر سرنگ ثبت شده است",
    summary:
      "کیارا ریجو در جعبه سه‌سرنگی عرضه می‌شود؛ هر سرنگ ۲٫۲ میلی‌لیتر و حجم کل ۶٫۶ میلی‌لیتر است. قیمت فهرست برای یک سرنگ ثبت شده تا کاربر قیمت هر واحد را با قیمت جعبه کامل اشتباه نگیرد.",
    audience: professionalAudience,
    features: ["۳ سرنگ ۲٫۲ میلی‌لیتری", "مجموع حجم جعبه: ۶٫۶ میلی‌لیتر", "قیمت نمایش‌داده‌شده برای هر سرنگ"],
    specs: [["نام", "KIARA REJU"], ["سازنده درج‌شده", "BioPlus"], ["کشور سازنده", "کره جنوبی"], ["تعداد", "۳ سرنگ"], ["حجم هر سرنگ", "۲٫۲ میلی‌لیتر"], ["حجم کل", "۶٫۶ میلی‌لیتر"]],
    checks: ["قیمت و تعداد به‌صورت یک سرنگ یا جعبه کامل روشن شود.", "سه بلیستر ۲٫۲ میلی‌لیتری در جعبه کامل کنترل شود.", "نام، بچ‌کد و تاریخ روی جعبه و هر سرنگ تطبیق داده شود."],
    faq: [{ question: "کیارا چند میل است؟", answer: "هر سرنگ ۲٫۲ میلی‌لیتر است و جعبه کامل سه سرنگ، یعنی مجموع ۶٫۶ میلی‌لیتر دارد." }, { question: "قیمت برای جعبه سه‌تایی است؟", answer: "در این صفحه قیمت فهرست برای هر سرنگ ثبت شده؛ قیمت جعبه کامل هنگام استعلام اعلام می‌شود." }],
  },
  {
    slug: "jalupro-hmw",
    nameFa: "جالپرو",
    nameEn: "JALUPRO",
    brand: "Jalupro / Professional Derma",
    category: "skin-boosters",
    type: "خانواده محصولات جالپرو",
    volume: "Classic، HMW و Super Hydro",
    priceToman: 14500000,
    priceNote: "مدل را انتخاب کنید",
    badge: "۳ مدل موجود",
    image: "/images/products/jalupro-classic.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Jalupro / Professional Derma",
    sourceUrl: "https://md.jalupro.com/?page_id=543",
    reviewedAt,
    sourceStatus: "نام و ساختار هر سه مدل با صفحات و پک‌شات‌های Jalupro تطبیق شد",
    summary:
      "جالپرو در سه مدل Classic، HMW یا همان جعبه صورتی، و Super Hydro موجود است. این سه مدل بسته‌بندی و حجم یکسانی ندارند؛ انتخاب‌گر صفحه عکس، قیمت، حجم و محتویات دقیق همان مدل را بدون جابه‌جایی صفحه نشان می‌دهد.",
    audience: professionalAudience,
    features: ["Classic با دو ست ۳ میلی‌لیتری", "HMW با سرنگ ۱٫۵ و ویال ۱ میلی‌لیتری", "Super Hydro با یک سرنگ ۲٫۵ میلی‌لیتری"],
    specs: [["برند", "JALUPRO"], ["شرکت", "Professional Derma SA"], ["کشور شرکت", "سوئیس"], ["مدل‌ها", "Classic، HMW، Super Hydro"], ["نکته", "حجم و اجزای هر مدل متفاوت است"]],
    checks: ["نام دقیق Classic، HMW یا Super Hydro روی جعبه با سفارش تطبیق داده شود.", "تعداد اجزای داخل بسته بر اساس مدل انتخابی کنترل شود.", "بچ‌کد، تاریخ و پلمب همه اجزای بسته ثبت شود."],
    faq: [{ question: "جالپرو صورتی کدام مدل است؟", answer: "در بازار ایران معمولاً جعبه صورتی به مدل HMW اشاره دارد. برای اطمینان، عبارت JALUPRO HMW روی جعبه معیار است." }, { question: "حجم هر سه مدل یکی است؟", answer: "خیر. Classic دو ست ۳ میلی‌لیتری، HMW یک سرنگ ۱٫۵ به‌همراه ویال ۱ میلی‌لیتری، و Super Hydro یک سرنگ ۲٫۵ میلی‌لیتری دارد." }],
    variants: [
      { id: "classic", label: "Classic", nameFa: "جالپرو کلاسیک", nameEn: "JALUPRO Classic", image: "/images/products/jalupro-classic.webp", imageAlt: "بسته واقعی جالپرو کلاسیک با ادیت مینیمال", imageVerified: true, volume: "۲ ست؛ هر ست محلول ۳ میلی‌لیتری + ویال آمینواسید", summary: "جالپرو Classic یک بسته دو‌نوبتی است. هر ست از محلول ۳ میلی‌لیتری و جزء جداگانه آمینواسید تشکیل می‌شود؛ تعداد چهار جزء داخل جعبه پیش از تحویل کنترل می‌شود.", features: ["۲ محلول ۳ میلی‌لیتری", "۲ ویال آمینواسید", "بسته دو‌نوبتی"], specs: [["مدل", "JALUPRO Classic"], ["محتویات", "۲ × محلول ۳ mL + ۲ × ویال آمینواسید"], ["تعداد ست", "۲"]], priceToman: 14500000, priceNote: "هر جعبه Classic", sourceName: "Jalupro — Classic", sourceUrl: "https://md.jalupro.com/?p=23" },
      { id: "hmw", label: "HMW · صورتی", nameFa: "جالپرو اچ‌ام‌دبلیو (صورتی)", nameEn: "JALUPRO HMW", image: "/images/products/jalupro-hmw.webp", imageAlt: "بسته واقعی جالپرو HMW صورتی با ادیت مینیمال", imageVerified: true, volume: "سرنگ ۱٫۵ میلی‌لیتری + ویال ۱ میلی‌لیتری", summary: "جالپرو HMW همان مدلی است که در بازار ایران با عنوان «صورتی» شناخته می‌شود. بسته از یک سرنگ ۱٫۵ میلی‌لیتری و یک ویال ۱ میلی‌لیتری تشکیل شده است.", features: ["مدل HMW", "سرنگ ۱٫۵ میلی‌لیتری", "ویال ۱ میلی‌لیتری"], specs: [["مدل", "JALUPRO HMW"], ["سرنگ", "۱٫۵ میلی‌لیتر"], ["ویال", "۱ میلی‌لیتر"]], priceToman: 14200000, priceNote: "هر جعبه HMW", sourceName: "Jalupro — HMW", sourceUrl: "https://md.jalupro.com/?p=25" },
      { id: "super-hydro", label: "Super Hydro", nameFa: "جالپرو سوپر هیدرو", nameEn: "JALUPRO Super Hydro", image: "/images/products/jalupro-super-hydro.webp", imageAlt: "بسته واقعی جالپرو سوپر هیدرو با ادیت مینیمال", imageVerified: true, volume: "۱ سرنگ از پیش پرشده ۲٫۵ میلی‌لیتری", summary: "جالپرو Super Hydro یک سرنگ آماده ۲٫۵ میلی‌لیتری دارد. این مدل از نظر جعبه و محتویات با Classic و HMW متفاوت است و قیمت جداگانه دارد.", features: ["مدل Super Hydro", "۱ × ۲٫۵ میلی‌لیتر", "یک سرنگ آماده"], specs: [["مدل", "JALUPRO Super Hydro"], ["حجم", "۱ × ۲٫۵ میلی‌لیتر"], ["شکل بسته", "سرنگ از پیش پرشده"]], priceToman: 18500000, priceNote: "هر جعبه Super Hydro", sourceName: "Jalupro — Super Hydro", sourceUrl: "https://md.jalupro.com/?p=774" },
    ],
  },
  {
    slug: "masport",
    nameFa: "مصپورت ۵۰۰ واحد",
    nameEn: "MASPORT 500 U",
    brand: "Masport / Masoondarou",
    category: "botulinum-toxins",
    type: "پودر بوتولینوم نوع A در ویال",
    volume: "۱ ویال ۵۰۰ واحدی همراه حلال طبق بسته",
    priceToman: 971000,
    priceNote: "هر بسته ۵۰۰ واحدی",
    image: "/images/products/masport-500.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Masoondarou — MASPORT 500",
    sourceUrl: "https://masoondarou.com/product/masport/",
    reviewedAt,
    sourceStatus: "نام، قدرت ۵۰۰ واحد و شرایط زنجیره سرد با اطلاعات سازنده تطبیق شد",
    summary:
      "مصپورت ۵۰۰ محصول ایرانی در ویال ۵۰۰ واحدی است. قیمت ۹۷۱ هزار تومان دقیقاً از فهرست فعلی وارد شده و صفحه آن را به عدد گرد تبدیل نمی‌کند. تحویل فقط با کنترل نام، قدرت، بچ، تاریخ و شرایط نگهداری همان بسته انجام می‌شود.",
    audience: professionalAudience,
    features: ["قدرت درج‌شده: ۵۰۰ واحد", "ساخت ایران", "نیازمند حفظ شرایط نگهداری درج‌شده روی بسته"],
    specs: [["نام", "MASPORT 500"], ["قدرت", "۵۰۰ واحد در هر ویال"], ["سازنده", "Masoondarou Biopharma"], ["کشور سازنده", "ایران"], ["واحد قیمت", "هر بسته"]],
    checks: ["عدد 500 U روی جعبه و ویال یکسان باشد.", "بچ‌کد، تاریخ، پلمب و حلال داخل بسته کنترل شود.", "دمای حمل و سابقه نگهداری پیش از پذیرش بررسی شود."],
    faq: [{ question: "مصپورت موجود چند واحد است؟", answer: "مدل موجود ۵۰۰ واحدی است." }, { question: "قیمت دقیق چند است؟", answer: "طبق تصویر فهرست موجودی، ۹۷۱٬۰۰۰ تومان برای هر بسته ۵۰۰ واحدی ثبت شده است." }],
  },
  {
    slug: "dyston-500",
    nameFa: "دیستون ۵۰۰ واحد",
    nameEn: "DYSTON 500 U",
    brand: "Dyston / Atra Zist Aray",
    category: "botulinum-toxins",
    type: "پودر بوتولینوم نوع A در ویال",
    volume: "۱ ویال ۵۰۰ واحدی",
    priceToman: 900000,
    priceNote: "هر بسته ۵۰۰ واحدی",
    image: "/images/products/dyston-500.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Atra Zist Aray — Iranian botulinum toxin",
    sourceUrl: "https://atrazistaray.com/en/products-and-technologies/iranian-botulinum-toxin/",
    reviewedAt,
    sourceStatus: "محصول ایرانی و قدرت ۵۰۰ واحدی با منابع سازنده و تصویر بسته تطبیق شد",
    summary:
      "دیستون موجودی فعلی مدل ۵۰۰ واحدی و تولید ایران است. قیمت برای یک ویال ثبت شده و واحد آن نباید با برندهای دیگر تبدیل یک‌به‌یک شود؛ نام محصول، عدد ۵۰۰ و شرایط نگهداری همان بسته معیار تحویل است.",
    audience: professionalAudience,
    features: ["۱ ویال ۵۰۰ واحدی", "تولید ایران", "قیمت برای هر بسته"],
    specs: [["نام", "DYSTON"], ["قدرت", "۵۰۰ واحد در هر ویال"], ["کشور", "ایران"], ["واحد قیمت", "هر بسته"]],
    checks: ["عدد 500 IU روی جعبه و ویال تطبیق داده شود.", "نام دیستون، بچ‌کد، تاریخ و پلمب بررسی شود.", "شرایط حمل سرد و دمای نگهداری همان بروشور کنترل شود."],
    faq: [{ question: "دیستون موجود چند واحد است؟", answer: "مدل این صفحه ۵۰۰ واحدی است." }, { question: "آیا ۵۰۰ واحد دیستون با ۵۰۰ واحد هر برند دیگری یکی است؟", answer: "نباید خودکار معادل در نظر گرفته شود؛ هر برند بروشور و روش مصرف خودش را دارد و تصمیم با فرد واجد صلاحیت است." }],
  },
  {
    slug: "liporase-1500",
    nameFa: "آنزیم کره‌ای لیپوریز ۱۵۰۰",
    nameEn: "LIPORASE Hyaluronidase 1500 IU",
    brand: "Liporase / Daehan New Pharm",
    category: "hyaluronidase-products",
    type: "آنزیم هیالورونیداز کره‌ای",
    volume: "هر ویال ۱۵۰۰ واحد؛ جعبه ۱۰ ویالی",
    priceToman: 980000,
    priceNote: "قیمت هر ویال؛ جعبه کامل ۱۰ ویال دارد",
    image: "/images/products/liporase-1500.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "Daehan New Pharm — Liporase",
    sourceUrl: "https://dhnp.co.kr/en/m23_view.php?cate=1&idx=263",
    reviewedAt,
    sourceStatus: "قدرت ۱۵۰۰ واحد در هر ویال با صفحه سازنده تطبیق شد؛ قیمت فهرست به‌صورت هر ویال ثبت شده است",
    summary:
      "منظور از «آنزیم کره‌ای» در این فهرست، لیپوریز ۱۵۰۰ واحد Daehan New Pharm است. جعبه کامل ۱۰ ویال دارد، اما قیمت برای هر ویال ثبت شده تا هزینه یک عدد با قیمت جعبه اشتباه نشود.",
    audience: professionalAudience,
    features: ["۱۵۰۰ واحد در هر ویال", "جعبه کامل ۱۰ ویال", "ساخت کره جنوبی"],
    specs: [["نام", "LIPORASE"], ["سازنده", "Daehan New Pharm"], ["کشور سازنده", "کره جنوبی"], ["قدرت", "۱۵۰۰ IU در هر ویال"], ["تعداد جعبه", "۱۰ ویال"], ["واحد قیمت", "هر ویال"]],
    checks: ["نام Liporase و عدد 1500 IU روی جعبه و ویال یکسان باشد.", "تعداد سفارش به‌صورت ویال یا جعبه کامل روشن ثبت شود.", "بچ‌کد، تاریخ و سلامت درپوش هر ویال بررسی شود."],
    faq: [{ question: "آنزیم کره‌ای چند واحد است؟", answer: "هر ویال لیپوریز ۱۵۰۰ واحد دارد." }, { question: "قیمت برای جعبه ۱۰تایی است؟", answer: "خیر. قیمت ۹۸۰٬۰۰۰ تومان برای هر ویال ثبت شده است؛ جعبه کامل جداگانه استعلام می‌شود." }],
  },
  {
    slug: "hyalase-1500",
    nameFa: "هایالاز انگلیسی ۱۵۰۰",
    nameEn: "HYALASE 1500 I.U.",
    brand: "Hyalase / Wockhardt UK",
    category: "hyaluronidase-products",
    type: "آنزیم هیالورونیداز انگلیسی",
    volume: "۱۵۰۰ واحد در هر آمپول؛ جعبه ۱۰ آمپولی",
    priceToman: 3800000,
    priceNote: "واحد قیمت فهرست را هنگام استعلام تأیید کنید",
    image: "/images/products/hyalase-1500.webp",
    imageVerified: true,
    publishedInCatalog: true,
    sourceName: "UK electronic Medicines Compendium — Hyalase 1500 I.U.",
    sourceUrl: "https://www.medicines.org.uk/emc/product/1505/smpc",
    reviewedAt,
    sourceStatus: "نام، سازنده و قدرت ۱۵۰۰ واحدی با برگه رسمی انگلیس تطبیق شد؛ فهرست اولیه مشخص نکرده قیمت برای یک آمپول است یا جعبه",
    warning: "قبل از پرداخت مشخص کنید قیمت ۳٬۸۰۰٬۰۰۰ تومان برای یک آمپول است یا جعبه کامل.",
    summary:
      "هایالاز انگلیسی Wockhardt با قدرت ۱۵۰۰ واحد در هر آمپول عرضه می‌شود و جعبه کامل ۱۰ آمپول دارد. چون تصویر فهرست واحد قیمت را ننوشته، سایت مبلغ را نمایش می‌دهد اما پیش از سفارش صریحاً تعداد را دوباره می‌پرسد.",
    audience: professionalAudience,
    features: ["۱۵۰۰ واحد در هر آمپول", "جعبه کامل ۱۰ آمپولی", "ساخت Wockhardt UK"],
    specs: [["نام", "HYALASE 1500 I.U."], ["سازنده", "Wockhardt UK Ltd"], ["کشور سازنده", "بریتانیا"], ["قدرت", "۱۵۰۰ واحد در هر آمپول"], ["تعداد جعبه", "۱۰ آمپول"], ["واحد قیمت", "نیازمند تأیید هنگام استعلام"]],
    checks: ["نام Hyalase، عدد 1500 I.U. و Wockhardt روی جعبه بررسی شود.", "قبل از پرداخت روشن شود سفارش یک آمپول است یا جعبه ۱۰تایی.", "بچ‌کد، تاریخ و سلامت همه آمپول‌های تحویلی کنترل شود."],
    faq: [{ question: "هایالاز انگلیسی چند واحد است؟", answer: "هر آمپول ۱۵۰۰ واحد دارد و جعبه کامل ۱۰ آمپول است." }, { question: "قیمت ۳٬۸۰۰٬۰۰۰ تومان برای یک آمپول است؟", answer: "فهرست اولیه واحد را مشخص نکرده است؛ تعداد و مبلغ نهایی باید هنگام استعلام تأیید شود و سایت آن را حدس نمی‌زند." }],
  },
];
